#!/usr/bin/env bash

USAGE="Usage: $0 <last-cset-to-backout> [<last-cset-to-keep>]"
LASTBAD=${1?$USAGE}
LASTGOOD=${2:-"parents($LASTBAD)"}
hg diff -r "$LASTBAD" -r "$LASTGOOD" | hg qimport - -n backout
echo "Created backout of $LASTGOOD..$LASTBAD"
