#!/usr/bin/env bash

for i in $HOME/zspace/mozilla-* $HOME/zspace/B2G*/gecko; do
    if [ -d $i/.git ]; then
        echo $i
        pushd $i >/dev/null && git branch-tree && popd >/dev/null
        echo
    fi
done
