#!/usr/bin/env bash

# Usage: $0 [numpatches [branch]]

NUMPATCHES=${1-1}
DEFBRANCH=$(git branch | grep "^*" | cut -d " " -f 2)
BRANCH=${2:-$DEFBRANCH}
FBRANCH=${BRANCH//\//-}     # filename-safe branch name

mkdir ~/zspace/patches/old 2>/dev/null
mv ~/zspace/patches/*-$FBRANCH-* ~/zspace/patches/old/ 2>/dev/null

git log --reverse --oneline -$NUMPATCHES $BRANCH |
awk '{print NR, $1}' |
while read cnt sha; do
    git hgp $sha > ~/zspace/patches/$cnt-$FBRANCH-$sha
done
