#!/usr/bin/env bash

$HOME/zspace/valgrind-bin/bin/valgrind --leak-check=full --log-file="$HOME/zspace/%p.memcheck" \
    --smc-check=all-non-file --vex-iropt-register-updates=allregs-at-mem-access --show-mismatched-frees=no --read-inline-info=yes \
    $*
