#!/usr/bin/env bash

if [ ! -d obj-debug -o ! -d obj-ndebug -o ! -h .mozconfig ]; then
    echo "Error: please run from the top source directory!" > /dev/stderr
    exit 1;
fi

UNAME=$(uname)
TARGET=ndebug
if [ -n "$1" ]; then
    TARGET=debug
fi

ln -sf $HOME/zspace/configs/mozconfig.$UNAME-android-$TARGET .mozconfig
rm obj-android
ln -s obj-$TARGET obj-android
