#!/usr/bin/env bash

if [ -d ".hg" ]; then
    QUEUE=$(hg qqueue | grep active | cut -d " " -f 1)
    QUEUE=${QUEUE// /}
    CSET=$(hg log -l 1 | grep "changeset:" | cut -d ":" -f 2)
    CSET=${CSET// /}
    TAG=$(hg log -l 1 | grep "tag:" | head -1 | cut -d ":" -f 2)
    TAG=${TAG// /}
    NAME="bld_${QUEUE}_${CSET}_${TAG}"
    FOLDER="$HOME/zspace/builds/$NAME"
    if [ -e "$FOLDER" ]; then
        bkn "$FOLDER"
    fi
    mkdir "$FOLDER"
    cp obj-android/dist/fennec*.apk $FOLDER
    cp -R .hg/patches-$QUEUE $FOLDER/
    hg diff > $FOLDER/unstaged.diff
elif [ -d ".git" ]; then
    BRANCH=$(git branch | grep "*" | cut -d " " -f 2)
    BRANCH=${BRANCH// /}
    CSET=$(git log -1 --oneline | cut -d " " -f 1)
    NAME="bld_${BRANCH}_${CSET}"
    FOLDER="$HOME/zspace/builds/$NAME"
    if [ -e "$FOLDER" ]; then
        bkn "$FOLDER"
    fi
    mkdir "$FOLDER"
    cp obj-android/dist/fennec*.apk $FOLDER
    git format-patch -o $FOLDER master
    git diff --cached > $FOLDER/staged.diff
    git diff > $FOLDER/unstaged.diff
fi;
