#!/system/bin/sh
export TMPDIR=/data/data/org.mozilla.fennec_kats
exec /data/local/Inst/bin/valgrind --tool=massif --massif-out-file=/mnt/sdcard/massif.log --log-file=/mnt/sdcard/valgrind.log --error-limit=no $*
