#!/usr/bin/env bash

PATCH=${1?"Usage: $0 <hg-patch-file>"}
if [[ $PATCH == http:* ]] || [[ $PATCH == https:* ]]; then
    LOCAL=$(mktemp patchXXX)
    wget ${PATCH//\/rev\//\/raw-rev\/} -O - > $LOCAL
    RET=$?
    if [[ $RET -ne 0 ]]; then
        exit $RET
    fi
    PATCH=$LOCAL
fi

echo "Applying patch from $PATCH"

git apply --reject < $PATCH
RET=$?
if [[ $RET -ne 0 ]]; then
    exit $RET
fi

AUTHOR=$(head $PATCH | grep "^# User" | sed -e "s/# User //")
awk 'BEGIN { msg = "" } /^diff/ { print msg; exit } !/^#/ { if (length($0) > 0) { msg = msg $0 "\n" } }' $PATCH |
git commit -a --author="$AUTHOR" -F -
