#!/usr/bin/env bash

# Run this while your $PWD is the root of your mozilla-central tree

SEARCH=${1:-"webrender"}

find testing/web-platform/meta -name "*.ini" -type f |
sort |
while read file; do
    awk "/$SEARCH/ { print \"$file,\" \$0 }" $file
done
